apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: finance
    version: 1.0.0
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
